# This is a basic workflow that is manually triggered

name: build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "build.py"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "build.py"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python3
        uses: actions/setup-python@v5
        with:
          python-version: "3.8.x"

      - name:  Setup ndk and strart build
        run: |
          python3 build.py --setup_ndk --build_binary
          ls -al native/out/**
          echo "MAGISK_VERSION=$(cat magisk_config.prop | grep "magisk.versionCode=" | cut -d '=' -f 2)" >> "$GITHUB_ENV"
          echo "MAGISK_VERSION=$MAGISK_VERSION"

      - name: Compress out
        run: |
          7za a magisk_bins.7z native/out/*

      - name: Upload output to GH-Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "magisk_bins.7z"
          name: "magisk_bins-${{ env.MAGISK_VERSION }}"
          tag: "magisk_bins-${{ env.MAGISK_VERSION }}-${{ github.sha }}"
          bodyFile: "native/out/magisk_version.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
